//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 08:44:33 PM IST 
//


package com.terragoedge.xml.devices;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}id"/>
 *         &lt;element ref="{}type"/>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}controllerStrId"/>
 *         &lt;element ref="{}idOnController"/>
 *         &lt;element ref="{}categoryStrId"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}nodeTypeStrId"/>
 *           &lt;element ref="{}technologyStrId"/>
 *           &lt;element ref="{}modelName"/>
 *           &lt;element ref="{}address"/>
 *           &lt;element ref="{}functionId"/>
 *         &lt;/sequence>
 *         &lt;element ref="{}geoZoneNamesPath"/>
 *         &lt;element ref="{}geoZoneId"/>
 *         &lt;element ref="{}lat"/>
 *         &lt;element ref="{}lng"/>
 *         &lt;element ref="{}properties"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "type",
    "name",
    "controllerStrId",
    "idOnController",
    "categoryStrId",
    "nodeTypeStrId",
    "technologyStrId",
    "modelName",
    "address",
    "functionId",
    "geoZoneNamesPath",
    "geoZoneId",
    "lat",
    "lng",
    "properties"
})
@XmlRootElement(name = "SLVDevice")
public class SLVDevice {

    @XmlElement(required = true)
    protected BigInteger id;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String type;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String controllerStrId;
    @XmlElement(required = true)
    protected String idOnController;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String categoryStrId;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String nodeTypeStrId;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String technologyStrId;
    protected String modelName;
    protected String address;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String functionId;
    @XmlElement(required = true)
    protected String geoZoneNamesPath;
    @XmlElement(required = true)
    protected BigInteger geoZoneId;
    @XmlElement(required = true)
    protected BigDecimal lat;
    @XmlElement(required = true)
    protected BigDecimal lng;
    @XmlElement(required = true)
    protected Properties properties;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the controllerStrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControllerStrId() {
        return controllerStrId;
    }

    /**
     * Sets the value of the controllerStrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControllerStrId(String value) {
        this.controllerStrId = value;
    }

    /**
     * Gets the value of the idOnController property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public String getIdOnController() {
        return idOnController;
    }

    /**
     * Sets the value of the idOnController property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdOnController(String value) {
        this.idOnController = value;
    }

    /**
     * Gets the value of the categoryStrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryStrId() {
        return categoryStrId;
    }

    /**
     * Sets the value of the categoryStrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryStrId(String value) {
        this.categoryStrId = value;
    }

    /**
     * Gets the value of the nodeTypeStrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeTypeStrId() {
        return nodeTypeStrId;
    }

    /**
     * Sets the value of the nodeTypeStrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeTypeStrId(String value) {
        this.nodeTypeStrId = value;
    }

    /**
     * Gets the value of the technologyStrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnologyStrId() {
        return technologyStrId;
    }

    /**
     * Sets the value of the technologyStrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnologyStrId(String value) {
        this.technologyStrId = value;
    }

    /**
     * Gets the value of the modelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * Sets the value of the modelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelName(String value) {
        this.modelName = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the functionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunctionId() {
        return functionId;
    }

    /**
     * Sets the value of the functionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctionId(String value) {
        this.functionId = value;
    }

    /**
     * Gets the value of the geoZoneNamesPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeoZoneNamesPath() {
        return geoZoneNamesPath;
    }

    /**
     * Sets the value of the geoZoneNamesPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeoZoneNamesPath(String value) {
        this.geoZoneNamesPath = value;
    }

    /**
     * Gets the value of the geoZoneId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGeoZoneId() {
        return geoZoneId;
    }

    /**
     * Sets the value of the geoZoneId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGeoZoneId(BigInteger value) {
        this.geoZoneId = value;
    }

    /**
     * Gets the value of the lat property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLat() {
        return lat;
    }

    /**
     * Sets the value of the lat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLat(BigDecimal value) {
        this.lat = value;
    }

    /**
     * Gets the value of the lng property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLng() {
        return lng;
    }

    /**
     * Sets the value of the lng property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLng(BigDecimal value) {
        this.lng = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link Properties }
     *     
     */
    public Properties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Properties }
     *     
     */
    public void setProperties(Properties value) {
        this.properties = value;
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SLVDevice other = (SLVDevice) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}
    
    

}
