package com.slvinterface.enumeration;

public enum ValType {
    MAC,FIXTURE,IDONCONTROLLER,EXISTING_MAC,FIXTURE_TYPE,LAMP_TYPE,LAMP_TYPE_OTHER,WATTAGE,WATTAGE_OTHER,SUPPLY_TYPE,
    SERIAL_NUMBER,PART_NUMBER,LUMINAIRE_MODEL,POLE_MATERIAL,POLE_STATUS,IDONCONTROLLER_SUFFIX;
}
