package com.slvinterface.enumeration;

public enum ValType {
    NAME,IDONCONTROLLER,GEOZONE,CALENDAR,CLIENT_NAME,DEVICE_PREMISE,ADDRESS,CLIENT_NUMBER,RoadUSRN,WATTAGE,
    MAC,FIXTURE_QR,EXISTING_MAC,DATE;

    }
